### ISSUE TITLE
No [tool.poetry] section in pyproject.toml

### ISSUE THREAD

**Issue by erlebach** [fkodom/yet-another-retnet#14]
To help fix my error (see previous issue), I decided to run you pyproject.toml file. However, I get the error that there is no [tool.poetry] section. How do you run your `toml` file? Here is your `pyproject.toml` as of 2023-11-05_10:13: 
```
[build-system]
requires = ["setuptools", "setuptools-scm"]

[project]
authors = [
  {name = "Frank Odom", email = "fodom@plainsight.ai"},
]
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
  # TODO: Check version ranges and pin dependencies
  "einops",
  "torch>=1.8",
]
description = "yet-another-retnet"
dynamic = ["version", "readme"] # NOTE: Must be in sync with [tool.setuptools.dynamic] below
license = {text = "MIT"}
name = "yet-another-retnet"
requires-python = ">=3.8"

[tool.setuptools.dynamic]
# NOTE: Must be in sync with 'project.dynamic' above
readme = {file = ["README.md"], content-type = "text/markdown"}
version = {attr = "yet_another_retnet.VERSION"}

[tool.setuptools.packages.find]
exclude = ["tests"]

# extra packages (e.g. pip install .[test])
[project.optional-dependencies]
test = [
  "black",
  "kaleido",
  "mypy",
  "pre-commit",
  "plotly",
  "pytest",
  "pytest-cov",
  "ruff",
  "types-requests",
]
train = [
  "lightning~=2.0.0",
  "tensorboard~=2.14.0",
  "tiktoken~=0.4.0",
  "torchdata>=0.6.0",
  "tqdm",
]

# ----- Linting, Formatting, and Typing -----

[tool.black]
line-length = 88

[tool.mypy]
check_untyped_defs = "true"
files = "yet_another_retnet/"
ignore_missing_imports = "true"

[tool.pytest.ini_options]
addopts = "--cov --cov-report term-missing --cov-fail-under 80"
filterwarnings = "ignore:.*.:DeprecationWarning"
testpaths = ["tests"]

[tool.ruff]
ignore = ["B905", "E501"]
line-length = 88
select = [
  "B",
  "C",
  "E",
  "F",
  "I",
  "W",
]
# Exclude a variety of commonly ignored directories.
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "venv",
]

[tool.ruff.mccabe]
max-complexity = 18
```

**Comment by fkodom** [comment]
@erlebach I'm not usually a `poetry` user.  But as [described in the README](https://github.com/fkodom/yet-another-retnet#install), you should be able to `pip install` this project.  

From my (very) limited understanding, `poetry` is sort of a convenience wrapper around `pip`, which also handles virtual environments?  If I'm missing something critical, please let me know.

**Comment by erlebach** [comment]
The beauty of poetry is that (like a requirement.txt) file, it is portable from one place to another. Creating the virtual environment is much more sophisticated. Just type "poetry install" and the proper environment is constructed. I fixed the problem by simply adding the missing section. What I don't understand is why the author of this repository included a pyproject.toml file that doesn't work. Thanks for responding!

**Comment by fkodom** [comment]
@erlebach I am the author of this repository.  🙃 

As I mentioned earlier and [described in the README](https://github.com/fkodom/yet-another-retnet#install), the provided `pyproject.toml` does allow for `pip install -e .` which should be more than enough.  Pyproject is now standard for all `pip`-installable Python projects -- not just `poetry`.

Using `poetry` for virtual environments should not preclude you from installing with `pip`.  You seem to be forcing a generic Python project into a very specific `poetry`-sized hole. 😅  But again, I'm not a regular `poetry` user, so it's hard to comment on what gave you trouble.
