### ISSUE TITLE
About activation function

### ISSUE THREAD

**Issue by Dongyeongkim** [fkodom/yet-another-retnet#6]
https://github.com/fkodom/yet-another-retnet/blob/ee3979c7535b9f79a3020cb098d6b97f143bcd22/yet_another_retnet/retention.py#L16

I think this line should be F.silu rather than F.relu.

Thanks for reading.

Reference

- https://pytorch.org/docs/stable/generated/torch.nn.functional.silu.html

**Comment by fkodom** [comment]
@Dongyeongkim Definitely -- thanks for catching this.  Feel free to open a PR, otherwise I will patch it this morning. 👍

**Comment by Dongyeongkim** [comment]
I have opened the pr. 

Thanks for fast reply
