### ISSUE TITLE
Have you ever tried Retnet for vision tasks?

### ISSUE THREAD

**Issue by cnyvfang** [fkodom/yet-another-retnet#9]
Hi, Thank you for your great work. The Retnet version you provided is the easiest to understand and clear to understand version I have ever seen. 
Have you ever tried using retnet module for visual tasks (instead of transformer)? If you've tried it, I'm curious how it turned out.
Thank you for your work again!

**Comment by fkodom** [comment]
Hi @cnyvfang, sorry for the late response.  I haven't really tried RetNet for vision-related tasks.  The main benefit of RetNet is for auto-regressive tasks, where the recurrent formulation can provide a significant speedup.  Vision tasks like classification, segmentation, and object detection don't benefit from the recurrent formulation.

Hope this helps!

**Comment by cnyvfang** [comment]
Got it, Thank you for your help!

**Comment by nigelnew** [comment]
https://arxiv.org/abs/2309.11523
https://www.researchgate.net/publication/374556167_RetSeg_Retention-based_Network_for_Polyps_Segmentation
These are two papers utilizing RetNet blocks instead of transformer blocks for vision tasks, they do change some parts in the original RetNet to make it work.

**Comment by fkodom** [comment]
Thanks for sharing!  Screenshot from the first paper:
<img width="455" alt="Screen Shot 2023-11-08 at 8 05 35 AM" src="https://github.com/fkodom/yet-another-retnet/assets/45951340/90b2a5e8-e62e-49ea-979a-d0c7d836c143">

The recurrent formulation is not used at all -- only parallel formulation like ordinary transformers.  Interesting that they used "retention" as a starting point, but IMO the end result is very different from RetNet. 🙂
